🤖 Add .meta/config.json file for concepts
exercism/elixir pull request #702
Opened 2021-04-02 06:37 UTC by ErikSchierboom

_TL;DR; Add authors/contributors to a new `concepts/<slug>/.meta/config.json` to Concepts in the same way you have for Concept Exercises._

---

To properly attribute authorship/contributorship for an individual concept, each concept will have its own `.meta/config.json` file with `authors` and `contributors` keys like those for concept and practice exercises. We're also moving the concept's blurb from the track's `config.json` to the `.meta/config.json` file, also similar to concept and practice exercises.

See https://github.com/exercism/docs/pull/96/files for the update to the specification.

This PR adds a `.meta/config.json` file for all concepts found in the track's `config.json` file containing:

- A `blurb` key, which value is copied from the `config.json` file and subsequently removed from the `config.json` file
- An `authors` key, the value of which is an empty array  
- A `contributors` key, the value of which is an empty array

## Maintainers TODO list

These are the things you, the maintainers, should do:

- [ ] Add the authors
- [ ] Add the contributors (if any)

**For clarity, authors should be the people who originally created the concept documents on this track. Contributors should be people who have substantially contributed to the concept documents. PRs for typos or multiple-concept PRs do not automatically mean someone should be considered a contributor to that concept. Those non-concept-specific contributions will get recognition through Exercism's reputation system in v3.**

You can either update this PR by pushing a new commit to this PR, or merge this and do a follow-up PR later. The former has the disadvantage that once we've added linting rules to `configlet` for the concept `.meta/config.json` file, the configlet CI check will start failing. 

## Tracking

https://github.com/exercism/v3-launch/issues/27

2021-04-02 12:57 UTC, ErikSchierboom commented
Following a suggestion that was made, we've updated the PR to pre-populate the authors/contributors with the authors/contributors of the exercise that teaches the concept (if any). This gives us a nice starting point, as the concept documents used to be exercise documents. You, the maintainers, should check to see if the authors/contributors are correct and add missing authors/contributors.

2021-04-02 13:36 UTC, neenjaw requested changes
@angelikatyborska I think you were missed on the concepts that I authored that I'm pretty sure you had a hand in reviewing.  Any other changes needed?

2021-04-02 13:36 UTC, neenjaw commented on concepts/anonymous-functions/.meta/config.json
> +  "contributors": []
```suggestion
  "contributors": [
    "angelikatyborska"
  ]
```

2021-04-02 13:36 UTC, neenjaw commented on concepts/atoms/.meta/config.json
> +  "contributors": []
```suggestion
  "contributors": [
    "angelikatyborska"
  ]
```

2021-04-02 13:36 UTC, neenjaw commented on concepts/bit-manipulation/.meta/config.json
> +  "contributors": []
```suggestion
  "contributors": [
    "angelikatyborska"
  ]
```

2021-04-02 13:36 UTC, neenjaw commented on concepts/cond/.meta/config.json
> +  "contributors": []
```suggestion
  "contributors": [
    "angelikatyborska"
  ]
```

2021-04-02 13:36 UTC, neenjaw commented on concepts/file/.meta/config.json
> +  "contributors": []
```suggestion
  "contributors": [
    "neenjaw"
  ]
```

2021-04-02 13:36 UTC, neenjaw commented on concepts/maps/.meta/config.json
> +  "contributors": []
```suggestion
  "contributors": [
    "angelikatyborska"
  ]
```

2021-04-02 13:36 UTC, neenjaw commented on concepts/module-attributes-as-constants/.meta/config.json
> +  "contributors": []
```suggestion
  "contributors": [
    "angelikatyborska"
  ]
```

2021-04-03 12:14 UTC, angelikatyborska commented
@neenjaw I have to reject all of your requests about adding me to those concepts 😅 

According to https://github.com/exercism/v3/pull/1335, I was *NOT* involved in the concepts: `anonymous-functions` and `bit-manipulation`

According to https://github.com/exercism/v3/pull/1129, I was *NOT* involved in the concepts: `cond` and `atoms`

According to https://github.com/exercism/v3/pull/1336, I was *NOT* involved in the concepts `maps` and `module-attributes-as-constants`

However, you were involved in `file` (https://github.com/exercism/v3/pull/2958) and I pushed a commit to mark that in both the concept's and the exercise's config.

2021-04-03 12:14 UTC, angelikatyborska approved these changes

2021-04-03 13:47 UTC, neenjaw commented
Weird. I don't remember who did have a hand in those PRs if not you...

2021-04-03 14:50 UTC, neenjaw approved these changes

2021-04-03 14:55 UTC, merged