Dont shadow kernel length
exercism/elixir pull request #935
Opened 2021-09-25 01:27 UTC by Cohen-Carlisle

At least one student has reported that defining length/1 warns that doing so conflicts with the automatically imported function Kernel.length/1, and it seems generally prudent not to shadow Kernel functions.

2021-09-25 08:28 UTC, jiegillet approved these changes
I think this is an excellent change, thank you!

2021-09-25 08:52 UTC, angelikatyborska requested changes
I... disagree. We can't change the instructions. They will be overwritten the next time we autoupdate exercises from problem specifications. Couldn't this also be solved by adding `import Kernel, except: [length: 1]` to the solution stub?

2021-09-25 08:55 UTC, jiegillet commented
Oh, my bad! Somehow I though this was a concept exercise. Sorry!

This could be solved by adding `import Kernel, except: [length: 1]`, but I feel that the name change is a cleaner solution.

2021-09-26 15:44 UTC, Cohen-Carlisle commented
Small update: This only causes a compilation error if you invoke the local function in your module. For example, I can define:
```
iex(1)> defmodule A do
...(1)> def length(_), do: 1
...(1)> end
{:module, A,
 <<70, 79, 82, 49, 0, 0, 4, 180, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 134,
   0, 0, 0, 14, 8, 69, 108, 105, 120, 105, 114, 46, 65, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 10, 97, 116, 116, 114, ...>>, {:length, 1}}
```
just fine. But If I do this:
```
iex(2)> defmodule B do
...(2)> def length(_), do: 1
...(2)> def test(b), do: length(b)
...(2)> end
** (CompileError) iex:3: imported Kernel.length/1 conflicts with local function
    (elixir 1.12.2) src/elixir_locals.erl:94: :elixir_locals."-ensure_no_import_conflict/3-lc$^0/1-0-"/2
    (elixir 1.12.2) src/elixir_locals.erl:95: anonymous fn/3 in :elixir_locals.ensure_no_import_conflict/3 
```
then I get the CompileError.

2021-09-27 07:25 UTC, angelikatyborska approved these changes

2021-09-27 07:26 UTC, merged